apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dspace
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: dspace-prod-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
