replicaCount: 3

image:
  tag: latest

ingress:
  hosts:
    - host: dspace.sugarkube.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: dspace-prod-tls
      hosts:
        - dspace.sugarkube.cloud

env:
  secrets:
    - name: METRICS_TOKEN
      secretName: dspace-prod-secrets
      secretKey: metrics-token

persistence:
  enabled: true
  size: 10Gi
  storageClass: longhorn

serviceMonitor:
  enabled: true
  namespace: monitoring

networkPolicy:
  egress:
    additional:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
        ports:
          - protocol: TCP
            port: 443
