apiVersion: v2
name: dspace
# Keep this version in sync with docs/apps/dspace.version for sugarkube installs.
version: 3.0.0
description: Helm chart for deploying the DSPACE application
type: application
appVersion: "v3.0.0"
