/**
 * @jest-environment jsdom
 */
import { beforeEach, afterEach, describe, it, expect } from 'vitest';
import '@testing-library/jest-dom';
import { render, fireEvent, waitFor, act } from '@testing-library/svelte';
import { jest } from 'vitest';

import QuestForm from '../src/components/svelte/QuestForm.svelte';
import {
    DEFAULT_DIALOGUE_NODE_ID,
    DEFAULT_DIALOGUE_TEXT,
    DEFAULT_NPC_NAME,
    DEFAULT_QUEST_IMAGE,
} from '../src/utils/questDefaults.js';

const questsAddMock = jest.fn();
const listMock = jest.fn();

jest.mock('../src/utils/customcontent.js', () => ({
    db: {
        quests: {
            add: questsAddMock,
            update: jest.fn(),
            get: jest.fn(),
            delete: jest.fn(),
        },
        list: listMock,
    },
    ENTITY_TYPES: { QUEST: 'quest', ITEM: 'item' },
}));

jest.mock('../src/utils/customQuestValidation.js', () => ({
    validateQuestData: () => ({ valid: true, errors: [] }),
    validateQuestDependencies: () => true,
}));

jest.mock('../src/utils/questHelpers.js', () => ({
    isQuestTitleUnique: () => true,
}));

function setupDom() {
    document.body.innerHTML = `
        <div id="app">
            <div id="quest-form-container"></div>
        </div>
    `;
    return document.getElementById('quest-form-container');
}

describe('QuestForm default submissions', () => {
    let container;

    beforeEach(() => {
        container = setupDom();
        questsAddMock.mockReset();
        questsAddMock.mockResolvedValue('quest-123');
        listMock.mockReset();
        listMock.mockResolvedValue([]);
        global.__SSR__ = false;
        global.__BROWSER__ = true;
    });

    afterEach(() => {
        container.innerHTML = '';
    });

    it('accepts autogenerated defaults when creating a quest', async () => {
        const { getByLabelText, getByRole, queryByText } = render(QuestForm, {
            target: container,
            props: { existingQuests: [] },
        });

        await waitFor(() => expect(listMock).toHaveBeenCalled());

        await act(async () => {
            fireEvent.input(getByLabelText(/title\*/i), {
                target: { value: 'Autogenerated Quest' },
            });
            fireEvent.input(getByLabelText(/description\*/i), {
                target: { value: 'Quest created with autogenerated defaults.' },
            });
        });

        const submitButton = getByRole('button', { name: /create quest/i });
        await act(async () => {
            fireEvent.click(submitButton);
        });

        await waitFor(() => expect(questsAddMock).toHaveBeenCalledTimes(1));
        const savedQuest = questsAddMock.mock.calls[0][0];

        expect(savedQuest.image).toBe(DEFAULT_QUEST_IMAGE);
        expect(savedQuest.npc).toBe(DEFAULT_NPC_NAME);
        expect(savedQuest.start).toBe(DEFAULT_DIALOGUE_NODE_ID);
        expect(savedQuest.dialogue).toHaveLength(1);
        expect(savedQuest.dialogue[0].text).toBe(DEFAULT_DIALOGUE_TEXT);
        expect(queryByText('Image is required')).not.toBeInTheDocument();
        expect(queryByText('NPC is required')).not.toBeInTheDocument();
    });
});
