/**
 * @jest-environment jsdom
 */
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import '@testing-library/jest-dom';
import { fireEvent, render, waitFor } from '@testing-library/svelte';
import { jest } from 'vitest';

import QuestForm from '../src/components/svelte/QuestForm.svelte';

const questsAddMock = jest.fn();
const listMock = jest.fn();

jest.mock('../src/utils/customcontent.js', () => ({
    db: {
        quests: {
            add: questsAddMock,
            update: jest.fn(),
            get: jest.fn(),
            delete: jest.fn(),
        },
        list: listMock,
    },
    ENTITY_TYPES: { QUEST: 'quest', ITEM: 'item' },
}));

jest.mock('../src/utils/customQuestValidation.js', () => ({
    validateQuestData: () => ({ valid: true, errors: [] }),
    validateQuestDependencies: () => true,
}));

jest.mock('../src/utils/questHelpers.js', () => ({
    isQuestTitleUnique: () => true,
}));

describe('QuestForm finish option placeholder handling', () => {
    let container;

    beforeEach(() => {
        questsAddMock.mockReset();
        listMock.mockReset();
        listMock.mockResolvedValue([]);

        container = document.createElement('div');
        document.body.appendChild(container);

        global.__SSR__ = false;
        global.__BROWSER__ = true;
    });

    afterEach(() => {
        container?.remove();
    });

    it('replaces the autogenerated finish option instead of appending a duplicate', async () => {
        const {
            container: rendered,
            getByLabelText,
            getByRole,
        } = render(QuestForm, {
            target: container,
            props: { existingQuests: [] },
        });

        await waitFor(() => expect(listMock).toHaveBeenCalled());

        // Seed the required fields so validation passes when adding options.
        await fireEvent.input(getByLabelText(/title\*/i), {
            target: { value: 'Custom finish quest' },
        });
        await fireEvent.input(getByLabelText(/description\*/i), {
            target: { value: 'Quest with a custom finish option.' },
        });

        const existingOptionTexts = rendered.querySelectorAll(
            '.options-list .option-row input[id*="-text"]'
        );
        expect(existingOptionTexts).toHaveLength(1);
        expect(existingOptionTexts[0]).toHaveValue('Finish quest');

        await fireEvent.input(getByLabelText(/new option text/i), {
            target: { value: 'Wrap up the mission' },
        });
        const optionTypeSelect = rendered.querySelector('#option-type-start');
        await fireEvent.change(optionTypeSelect, { target: { value: 'finish' } });
        await fireEvent.click(getByRole('button', { name: /add option/i }));

        await waitFor(() => {
            const optionRows = rendered.querySelectorAll('.options-list .option-row');
            expect(optionRows).toHaveLength(1);

            const [rowInput] = optionRows[0].querySelectorAll('input[type="text"]');
            expect(rowInput).toHaveValue('Wrap up the mission');

            const [rowTypeSelect] = optionRows[0].getElementsByTagName('select');
            expect(rowTypeSelect).toHaveValue('finish');
        });
    });
});
