{{- if and .Values.secret.enabled (not (empty .Values.secret.stringData)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dspace.fullname" . }}
  labels:
    {{- include "dspace.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
