"""Group STL outputs into use-case artifacts with README guides.

This utility mirrors the Build STL Artifacts workflow used in the sugarkube repo and
includes the pi_carrier.scad source alongside the printable stack parts. It also moves the
carrier-level preview plates out of the carriers/ bundle into preview/ so the artifact only
ships real print surfaces in the carrier folder.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path


class PackagingError(RuntimeError):
    """Raised when expected STL inputs are missing."""


def _ensure_exists(path: Path) -> Path:
    if not path.exists():
        raise PackagingError(f"Missing required STL: {path}")
    return path


def _write_readme(
    path: Path,
    *,
    title: str,
    intro: str,
    layout: dict[str, list[Path]],
    docs: list[str],
) -> None:
    lines = [title, "", intro, "", "Contents:"]
    for subdir, sources in layout.items():
        lines.append(f"- {subdir}/")
        lines.extend(f"  - {source.name}" for source in sources)

    lines.extend(
        [
            "",
            "Docs:",
            *(f"- {doc}" for doc in docs),
            "- .github/workflows/scad-to-stl.yml",
            "",
            "These artifacts are generated by the Build STL Artifacts workflow.",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def _copy_into(dest_dir: Path, sources: list[Path]) -> None:
    dest_dir.mkdir(parents=True, exist_ok=True)
    for source in sources:
        shutil.copy2(_ensure_exists(source), dest_dir / source.name)


def package_stl_artifacts(*, stl_dir: Path, cad_dir: Path, out_dir: Path) -> None:
    if not stl_dir.exists():
        raise PackagingError(f"STL directory not found: {stl_dir}")

    stack_dir = stl_dir / "pi_cluster"
    pi_carrier_source = cad_dir / "pi_cluster" / "pi_carrier.scad"

    artifacts = {
        "pi_cluster_stack": {
            "title": "Pi cluster stack STLs",
            "intro": "Modular plates + posts + fan adapter plus fan-wall matrices.",
            "layout": {
                "carriers": [pi_carrier_source],
                "posts": [stack_dir / "posts" / "pi_carrier_stack_post.stl"],
                "fan_adapters": [
                    stack_dir / "fan_adapters" / "pi_carrier_stack_fan_adapter.stl"
                ],
                "fan_walls": sorted(
                    (stack_dir / "fan_walls").glob("pi_carrier_stack_fan_wall_fan*.stl")
                ),
                "preview": [
                    stack_dir / "carriers" / "printed" / "pi_carrier_stack_carrier_level_printed.stl",
                    stack_dir / "carriers" / "heatset" / "pi_carrier_stack_carrier_level_heatset.stl",
                    stack_dir / "preview" / "pi_carrier_stack_preview.stl",
                ],
            },
            "docs": [
                "docs/pi_cluster_stack.md",
                "docs/pi_cluster_stack_assembly.md",
            ],
        },
        "pi_cluster_carriers": {
            "title": "Pi carrier plates",
            "intro": "Standalone triple-Pi carriers for stack or flat deployments.",
            "layout": {
                "printed": [
                    stl_dir / "pi_carrier_printed.stl",
                    stl_dir / "pi5_triple_carrier_rot45_printed.stl",
                ],
                "heatset": [
                    stl_dir / "pi_carrier_heatset.stl",
                    stl_dir / "pi5_triple_carrier_rot45_heatset.stl",
                ],
            },
            "docs": [
                "docs/pi_cluster_carrier.md",
                "docs/pi_cluster_stack.md",
            ],
        },
        "sugarkube-enclosure": {
            "title": "Sugarkube enclosure",
            "intro": "Frame + panel brackets + shell grouped by standoff mode.",
            "layout": {
                "printed": [
                    stl_dir / "frame_printed.stl",
                    stl_dir / "panel_bracket_printed.stl",
                    stl_dir / "sugarkube_printed.stl",
                ],
                "heatset": [
                    stl_dir / "frame_heatset.stl",
                    stl_dir / "panel_bracket_heatset.stl",
                    stl_dir / "sugarkube_heatset.stl",
                ],
            },
            "docs": [
                "docs/build_guide.md",
                "docs/index.md",
            ],
        },
    }

    out_dir.mkdir(parents=True, exist_ok=True)

    for artifact_dir, config in artifacts.items():
        root = out_dir / artifact_dir
        if root.exists():
            shutil.rmtree(root)
        root.mkdir(parents=True)

        readme_layout: dict[str, list[Path]] = {}
        for subdir, sources in config["layout"].items():
            if not sources:
                raise PackagingError(f"No STL files found for {artifact_dir}/{subdir}")
            _copy_into(root / subdir, list(sources))
            readme_layout[subdir] = list(sources)

        _write_readme(
            root / "README.txt",
            title=config["title"],
            intro=config["intro"],
            layout=readme_layout,
            docs=config["docs"],
        )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Package STL outputs into grouped artifact directories.",
    )
    parser.add_argument(
        "--stl-dir",
        type=Path,
        default=Path("stl"),
        help="Directory containing rendered STL files (default: stl).",
    )
    parser.add_argument(
        "--cad-dir",
        type=Path,
        default=Path("cad"),
        help="Directory containing CAD sources for artifacts (default: cad).",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("dist/stl_artifacts"),
        help="Output directory where grouped artifacts will be staged (default: dist/stl_artifacts).",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        package_stl_artifacts(
            stl_dir=args.stl_dir,
            cad_dir=args.cad_dir,
            out_dir=args.out_dir,
        )
    except PackagingError as exc:
        parser.error(str(exc))
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
