apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: dspace
  namespace: dspace
spec:
  interval: 30m
  chart:
    spec:
      chart: deploy/charts/dspace
      sourceRef:
        kind: GitRepository
        name: dspace
        namespace: flux-system
      version: 0.1.1
      reconcileStrategy: ChartVersion
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: dspace-dev-values
      valuesKey: values.yaml
