import { expect, test } from '@playwright/test';
import { clearUserData, waitForHydration } from './test-helpers';

const TOP_NAV_ROUTES = ['/', '/quests', '/inventory', '/energy', '/wallet', '/profile', '/docs'];

const TOOLBOX_ROUTES = [
    '/toolbox',
    '/inventory/manage',
    '/processes/manage',
    '/quests/manage',
    '/inventory/create',
    '/processes/create',
    '/quests/create',
];

const chatMode = (process.env.REMOTE_CHAT_MODE || 'ui').toLowerCase();
const liveChatPrompt =
    process.env.REMOTE_CHAT_PROMPT || `Remote smoke ping ${new Date().toISOString()}`;

test.describe('Remote release smoke harness', () => {
    test.setTimeout(180_000);

    test.beforeEach(async ({ page }) => {
        await clearUserData(page);
        page.on('dialog', (dialog) => dialog.accept());
    });

    test('runs release sanity checks against a deployed base URL', async ({ page }) => {
        await test.step('app shell and key routes load', async () => {
            for (const route of TOP_NAV_ROUTES) {
                const response = await page.goto(route, { waitUntil: 'domcontentloaded' });
                expect(response?.status()).toBeLessThan(400);
                await waitForHydration(page);
                await expect(page.getByRole('main')).toBeVisible();
            }
        });

        await test.step('toolbox/editor/manage routes load', async () => {
            for (const route of TOOLBOX_ROUTES) {
                const response = await page.goto(route, { waitUntil: 'domcontentloaded' });
                expect(response?.status()).toBeLessThan(400);
                await waitForHydration(page);
                const heading = page.locator('main h1, main h2, main [role="heading"]').first();
                await expect(heading).toBeVisible();
            }
        });

        await test.step('simple quest interaction works', async () => {
            const response = await page.goto('/quests/welcome/howtodoquests');
            expect(response?.status()).toBeLessThan(400);
            await waitForHydration(page);

            const chatPanel = page.getByTestId('chat-panel');
            await expect(chatPanel).toBeVisible();
            await expect(chatPanel.locator('.npcDialogue')).toContainText('Greetings, adventurer');

            const firstStep = page.getByRole('button', { name: 'A quest, you say? Tell me more.' });
            await expect(firstStep).toBeVisible();
            await firstStep.click();
            await expect(chatPanel.locator('.npcDialogue')).toContainText(
                'Your quest, dear player'
            );
        });

        await test.step('process lifecycle sanity works (start/cancel or collect)', async () => {
            const response = await page.goto('/processes');
            expect(response?.status()).toBeLessThan(400);
            await waitForHydration(page, '.processes-page');

            const startButton = page.getByTestId('process-start-button').first();
            await expect(startButton).toBeVisible();
            await startButton.click();

            const collectButton = page.getByRole('button', { name: 'Collect' }).first();
            const cancelButton = page.getByRole('button', { name: 'Cancel' }).first();

            if (await collectButton.isVisible()) {
                await collectButton.click();
            } else {
                await expect(cancelButton).toBeVisible();
                await cancelButton.click();
            }

            await expect(page.getByTestId('process-start-button').first()).toBeVisible();
        });

        await test.step('custom item create/delete sanity works', async () => {
            const itemName = `Remote Smoke Item ${Date.now()}`;

            const createResponse = await page.goto('/inventory/create');
            expect(createResponse?.status()).toBeLessThan(400);
            await waitForHydration(page);

            await page.locator('#name').fill(itemName);
            await page
                .locator('#description')
                .fill('Temporary item generated by remote smoke harness.');
            await page.getByRole('button', { name: /^Create Item$/i }).click();

            const successBanner = page.getByRole('status');
            await expect(successBanner).toBeVisible();
            await expect(successBanner).toContainText('Item created successfully');

            const manageResponse = await page.goto('/inventory/manage');
            expect(manageResponse?.status()).toBeLessThan(400);
            await waitForHydration(page);

            const customRow = page.locator('.item-row').filter({ hasText: itemName }).first();
            await expect(customRow).toBeVisible();
            await customRow.getByRole('button', { name: 'Delete' }).click();
            await expect(customRow).toHaveCount(0);
        });

        await test.step('chat page availability and optional live mode', async () => {
            const response = await page.goto('/chat');
            expect(response?.status()).toBeLessThan(400);
            await waitForHydration(page);

            const chatPanel = page.locator('[data-testid="chat-panel"]');
            await expect(chatPanel).toBeVisible();
            await expect(chatPanel.getByRole('textbox')).toBeEnabled();

            if (chatMode !== 'live') {
                test.info().annotations.push({
                    type: 'chat-mode',
                    description: 'REMOTE_CHAT_MODE=ui (availability-only)',
                });
                return;
            }

            const textbox = chatPanel.getByRole('textbox');
            await textbox.fill(liveChatPrompt);
            await chatPanel.getByRole('button', { name: 'Send' }).click();

            await expect(chatPanel.getByText(liveChatPrompt)).toBeVisible();
            const assistantBubble = chatPanel.locator('.message-bubble.assistant').first();
            const chatError = chatPanel.locator('.chat-error').first();

            await expect
                .poll(async () => {
                    if (await assistantBubble.isVisible()) {
                        return 'assistant';
                    }
                    if (await chatError.isVisible()) {
                        return 'error';
                    }
                    return 'pending';
                })
                .not.toBe('pending');
        });
    });
});
