name: CI
on:
  push:
    branches: [v3]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with: { version: 9 }
      - run: pnpm install --frozen-lockfile
      - run: cd frontend && pnpm install --no-frozen-lockfile
      - name: Run & upload coverage
        run: |
          pnpm test:all
          # The upload commands inside package.json already add --flag
