name: link-check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: ./.github/actions/run-lychee
        with:
          version: "0.14.0"
          args: >-
            --accept 200,403,429,503
            --base-url https://democratized.space
            --exclude "http://localhost"
            --timeout 30
            --max-retries 2
            --retry-wait-time 5
            --no-progress --verbose
            "**/*.md"
          format: markdown
          output: lychee/out.md
